### ISSUE TITLE
To imrove UX add option for disabling Sleep feature on Mac entirely, if possible

### ISSUE THREAD

**Issue by neooleg** [pkamb/PowerKey#36] opened 2016-03-19 17:43 UTC
## Problem
If use Delete (which make sense because regular location) for Power button it doesn't work always. If user presses (taps) button fast, nothing happens, i.e. symbol doesn't erase. They erase only if big timespan between taping.

## Solution / Assumption
Probably, this is because OS tracks the button pressing and waiting for acting Sleep action. Thus, if possible to disable Sleep action for the Power button - it will help to work Delete action as usual button.

**Comment by pkamb** [comment] 2016-04-14 18:54
Thanks for opening this. Unfortunately, it doesn't seem to be possible to make the PowerKey behave exactly like a "normal" key. Seems like we'll have to deal with the slightly firmer key presses needed for the Power Key.

This issue is a duplicate of #1 - Quick successive key presses don't get registered 

If anyone has input or a solution for this issue lets please continue the discussion over there.

**Closed by pkamb** 2016-04-14 18:54 UTC
